### PR TITLE
Improved and Enhanced Footer

### PR DESCRIPTION
**Pull request by Elgayar**
The footer wasn't nice-looking, it wasn't responsive, the code wasn't
written well and it wasn't clean, no indentation and misuse of
attributes and several other things.

I fixed everything, made it responsive, somehow improved and enhanced
the design and made it look more professional!

Solving issue #39
Live Link: https://elgayar.github.io/pslab.fossasia.org/

### CODE REVIEW

**Comment by Elgayar** [comment]
Before: 
image

After:
image

**Comment by Elgayar** [comment]
@mariobehling

**Review by hemantjadon — COMMENTED** [review]
* Align the About PSLab items section to the left.

* The social icons should be circular I suppose, with a lower opacity.

Which issuse is this in regard with. Always mention the issue in the PR.

**Comment by Elgayar** [comment]
Done!
Fixing issue #39 
Live Link: https://elgayar.github.io/pslab.fossasia.org/
@hemantjadon

**Comment by hemantjadon** [comment]
I guess Contact section and social section below it will seem nicer. Your views @mariobehling

**Comment by Elgayar** [comment]
When will it get merged please?

**Comment by Elgayar** [comment]
@mariobehling @hemantjadon is there any amendments that I should do?

**Comment by mariobehling** [comment]
Thank you.

**Pull request merged**
