### PR TITLE
Fixes #63

### LINKED ISSUE #63: Add developers and mentors to website
* Devs
* Mentors: Praveen Patil (Gnovi), Kiwi, Darwin Gosal, Shams Jaber, Ansgar Schmidt, Haggen So, Victoria Bondarchuk, Wan Leung Wong, Mitch Altman, Greg Austic, Soong Chee Gi, Lorenz Gerber

### PR DESCRIPTION
**Pull request by Remorax**
This fixes issue #63.
All the mentors have been added as requested.
The changes can be viewed here: http://modest-payne-87394c.bitballoon.com/
All photos and data have been procured from the Internet.
Please review this ASAP :) @mariobehling @CloudyPadmal @wavicles @jigyasa-grover @abishekvashok

### CODE REVIEW

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
image

This is looking bit odd.

**Comment by Remorax** [comment]
It should be fine now @0x48piraj

**Comment by 0x48piraj** [comment]
Now, you're talking :fire:

**Review by 0x48piraj — APPROVED** [review]
LGTM! :+1: :sunglasses:

**Review by abishekvashok — APPROVED** [review]

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
