### PR TITLE
Improved the footer

### PR DESCRIPTION
**Pull request by sudo-panda**
Resolves issue #19 
[New](https://baidya99.github.io/pslab.fossasia.org)
[Original](http://pslab.fossasia.org/)

### CODE REVIEW

**Comment by sudo-panda** [comment]
Sorry for the spelling mistake in the commit.

**Comment by hemantjadon** [comment]
The hovers for email, slack channel and slack invite are not looking good. Please check.

**Comment by sudo-panda** [comment]
Now?

**Comment by hemantjadon** [comment]
You should use something like what is implemented in navbar for the hover.

**Comment by sudo-panda** [comment]
Is this all right? https://baidya99.github.io/pslab.fossasia.org/

**Comment by hemantjadon** [comment]
Try this for hover `color : rgba(255,255,255,0.8)`

**Comment by sudo-panda** [comment]
Changed it.

**Comment by hemantjadon** [comment]
Seems better now. Bur can you make it look like slack channel comes in one line only ?

Also squash the commits please.

**Comment by sudo-panda** [comment]
Can you give me a screen shot because I can see that the slack channel is is one line.
Also I have edited the files using the online editor and I don't know how to squash them in the online editor. If you could help me, please.

**Comment by mariobehling** [comment]
Looks good to me. Thanks.

**Pull request merged**
