### PR TITLE
Site rendering issue fixed for developer page, Added Favicon

### PR DESCRIPTION
**Pull request by ankitrgadiya**
Fixed Issue #14

### CODE REVIEW

**Comment by ankitrgadiya** [comment]
Fixed Issue #13

**Comment by ankitrgadiya** [comment]
As part of this [Task](https://codein.withgoogle.com/dashboard/task-instances/6247434432806912/)

**Comment by hemantjadon** [comment]
Can you squash the commits @ankitrgadiya ?

There are two ways in which you can squash.

* While pushing another commit, you can amend to the previous commit. `git commit --amend` (when you already have a commit existing and you want to amend to it) instead of doing `git commit -m "message"` every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 2 commits of yours which you want to squash into single, then the command goes `git rebase -i HEAD~2`. Which leads to an **editor** where you will be asked for every commit whether you want to `pick or squash`. type squash for all the 2 commits present and exit. The rebase continues and you have force push the changes, as in `git push -f origin <branch>`.

This might be a bit confusing, but please watch this [Video](https://www.youtube.com/watch?v=qh9KtjfjzCU)

**Comment by ankitrgadiya** [comment]
I can but is it necessary as both are solving different issues?

**Comment by ankitrgadiya** [comment]
Thanks! It was related to this [Task](https://codein.withgoogle.com/dashboard/task-instances/6247434432806912/)

**Pull request merged**
