### PR TITLE
issue #39 have fixed with svg logo

### PR DESCRIPTION
**Pull request by AKostiv8**
fixed the issue #39 added missed photo of mentor, fixed links and made
text readable in the mentor/developer section and made footer section
more user-friendly

### CODE REVIEW

**Comment by AKostiv8** [comment]
Live link https://akostiv8.github.io/pslab.fossasia.org/

**Comment by hemantjadon** [comment]
Looks good to me 👍

**Comment by mariobehling** [comment]
The mentor picture is wrong as mentioned before. Bottom area does not seem like a substantial improvement to before. Sorry, but I have to revert this.

**Comment by AKostiv8** [comment]
@mariobehling you consider that that is bottom section is better?

**Comment by AKostiv8** [comment]
For it is total mess

**Pull request merged**
