### PR TITLE
Updated meta description to Privacy Policy : https://github.com/fossasia/pslab.io/issues/149

### PR DESCRIPTION
**Pull request by shivaylamba**
https://github.com/fossasia/pslab.io/issues/149

### CODE REVIEW

**Review by abishekvashok — COMMENTED** [review]
Looks cool enough for a merge. But I would be happy if you could follow the guidelines: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

Moreover see the title, can you update that as well? And also open a relevant issue for this?

**Comment by shivaylamba** [comment]
I have updated the title and also opened an issue for the same Pull Request. Also I have gone through the blog article.

**Review by abishekvashok — APPROVED** [review]

**Comment by abishekvashok** [comment]
Mention the issue url on the pr body

**Comment by shivaylamba** [comment]
Have added the issue url

**Comment by shivaylamba** [comment]
@abishekvashok Oh so the pull request wasn't merged. Is something wrong with the PR?
@mariobehling Was there some issue with the PR sir?

**Pull request closed without merging**
