### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by AKostiv8**
solved issues with footer, navbar and made links under photos more user-friendly

### CODE REVIEW

**Comment by AKostiv8** [comment]
https://akostiv8.github.io/pslab.fossasia.org/

**Review by hemantjadon — COMMENTED** [review]
Always give the title of PR as `Fixes #XX: <Description of PR>`

The logo of gmail is wrong Please see that you use a flat SVG.

**Comment by mariobehling** [comment]
Thanks for your contribution. We are happy to get you onboard!

Unfortunately the photo is wrong and icons are not following the colors of the website. I don't see an issue where this PR has been discussed. Please open an issue discussing this changes first. Cheers. I am closing this PR therefore.

**Comment by robbyoconnor** [comment]
Also Merge conflicts

**Pull request closed without merging**
