### PR TITLE
Adding Developers section to the main page

### PR DESCRIPTION
**Pull request by nadunys**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Please add "Fixes #31" (no quotes)  to your initial description by clicking the pencil.

**Review by robbyoconnor — APPROVED** [review]
Looks Good To Me! [approving as part of GCI 16](https://codein.withgoogle.com/dashboard/task-instances/5939880230125568/).

**Comment by robbyoconnor** [comment]
@mariobehling I cannot merge this, but it [does what it needs to do](https://yashnadun.github.io/yashnadun/), according to #31.

**Comment by jigyasa-grover** [comment]
@robbyoconnor Merged it :)

**Pull request merged**
