### PR TITLE
Did the following changes.

### PR DESCRIPTION
**Pull request by dewanshrawat15**
I introduced slow scrolling in the web page. Also, i introduced the part like when you click on any link in the menu in the phone, the menu drawer closes. Plus I introduced a sleek scroll bar. And also the address bar color changes when you view it on a phone having android 5.0+. Also in iOS.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Squash your commits into one please. Also what did you fix?

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
squash and make your pr more descriptive

**Comment by robbyoconnor** [comment]
Also resolve your merge conflicts

**Comment by dewanshrawat15** [comment]
I introduced slow scrolling in the web page. Also, i introduced the part like when you click on any link in the menu in the phone, the menu drawer closes. Plus I introduced a sleek scroll bar. And also the address bar color changes when you view it on a phone having android 5.0+. Also in iOS.

**Comment by robbyoconnor** [comment]
Resolve merge conflicts.

**Review by jigyasa-grover — CHANGES_REQUESTED** [review]
* Squash all your commits into one and rename it to something meaningful.
* Also Provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful.

**Comment by hemantjadon** [comment]
Closing this as No response from 2 days. Please reopen when you want to work further on this.

**Pull request closed without merging**
