### PR TITLE
Centered the navbar.

### PR DESCRIPTION
**Pull request by sudo-panda**
Solves issue #16 
[New](baidya99.github.io/pslab.fossasia.org)
[Original](pslab.fossasia.org)

### CODE REVIEW

**Comment by hemantjadon** [comment]
@Baidya99  I think screenshots are not working They are linked to the repo.

**Comment by sudo-panda** [comment]
Sorry here it is https://baidya99.github.io/pslab.fossasia.org/

**Comment by hemantjadon** [comment]
This is how i am able to see it 
screen shot 2016-12-16 at 7 15 23 pm

**Comment by sudo-panda** [comment]
What is your screen size?

**Comment by sudo-panda** [comment]
The error is in Chrome.

**Comment by sudo-panda** [comment]
Got it.

**Comment by sudo-panda** [comment]
Solved it.

**Comment by sudo-panda** [comment]
Now try it.

**Comment by sudo-panda** [comment]
Will this be enough for this task: https://codein.withgoogle.com/dashboard/task-instances/5738115115253760/

**Pull request merged**
