### PR TITLE
Fixes issue #59 now items does not move on sliding

### PR DESCRIPTION
**Pull request by Rishabh-Kumar-Bothra**
### checklist 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` 
- [x] I have checked that my feature works correctly
- [x] I have added necessary documentation (if appropriate)
Please Review

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Nice work @geekychaser ! I checked the fix made by you and it almost looks good! :+1: 

But the same issue is happening when we scroll down and then hover on to those header links. They get bold and the links to the left will slide to left. This is quiet visible when hovered over `Developers and Mentors` link!

Can you address that one as well? : )

**Comment by Rishabh-Kumar-Bothra** [comment]
sure sir , let me try.
thank you

**Comment by Rishabh-Kumar-Bothra** [comment]
@CloudyPadmal please review sir.
thank you

**Review by CloudyPadmal — APPROVED** [review]
Nice work!! :D Thanks for the fix @geekychaser ! You can call us by names! No need of a sir! :) Hoping to see more contribution from you! :+1:

**Comment by Rishabh-Kumar-Bothra** [comment]
@CloudyPadmal i think this is perfect now for merge. please suggest if any other changes are being required.
thank you

**Comment by adsk261095** [comment]
@CloudyPadmal is the issue still open?

**Comment by CloudyPadmal** [comment]
Hi @adsk261095 ! It's resolved now. You can go through other [issues](https://github.com/fossasia/pslab.fossasia.org/issues) and start with any of them :)

**Comment by adsk261095** [comment]
image
But on scrolling down the "Home","Features" and other item are moving down.
Wasn't that the issue??

**Comment by CloudyPadmal** [comment]
Oh! It seems happening again. @adsk261095 can you make a fix?

**Comment by adsk261095** [comment]
Sure @CloudyPadmal let me make PR

**Pull request merged**
