### PR TITLE
dropdown expands on scroll over

### PR DESCRIPTION
**Pull request by alejoheredia**
@mariobehling Here I made the functionality to expand the dropdown on scroll over, you told me to do that on #29

### CODE REVIEW

**Comment by hemantjadon** [comment]
@Heredroky link to your gh-pages please so that we can check out and review.

**Comment by mariobehling** [comment]
* [x] Please link "Getting Started" to the "Installation" section
* [x] Please implement the scroll over dropdown effect as well for "Labs" (which was included in the meantime) and link "Labs" to http://labs.fossasia.org

**Comment by alejoheredia** [comment]
@mariobehling I've just done that, check it out: https://heredroky.github.io/pslab.fossasia.org/index.html

😄

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
