### PR TITLE
Centered the navbar

### PR DESCRIPTION
**Pull request by sudo-panda**
Solves issue #16 
[Changed](https://baidya99.github.io/pslab.fossasia.org/)
[Original](http://pslab.fossasia.org/index.html)

### CODE REVIEW

**Comment by hemantjadon** [comment]
@Baidya99 this two line design is not seeming good I guess

Navigation bar should be in one line only i guess.

**Comment by sudo-panda** [comment]
capture
On my pc it is in one line.

**Comment by sudo-panda** [comment]
I think I got the solution.

**Comment by sudo-panda** [comment]
I have to close this.

**Pull request closed without merging**
