### PR TITLE
Makes the top nav to change on scroll starts

### LINKED ISSUE #24: Keep top menu bar visible
The top bar disappears when scrolling down. Keep it visible.

### PR DESCRIPTION
**Pull request by abishekvashok**
Adopted the top bar to changes when scrolling starts and unified the links in the site to the same design throughout.

Closes #24 and #45 

Done as part of GCI Task: https://codein.withgoogle.com/dashboard/task-instances/6430794312581120/
Demo link: https://abhi2424shek.github.io/pslab.fossasia.org/

@mariobehling pls review.

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
Demo link ?

**Comment by abishekvashok** [comment]
@jig08 updated pls don't merge yet got some more code for another issue!

**Comment by abishekvashok** [comment]
@jig08 ready, pls review madam.

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
