### PR TITLE
Added 404 and 500 Pages

### LINKED ISSUE #87: No ERROR Pages present.
# Current State : 

#### Almost all the summit websites are using 404 and 500 **ERROR** pages.

# Ideal State : 

There should be **ERROR** Pages. :sparkles:

### PR DESCRIPTION
**Pull request by 0x48piraj**
### Preview Links : 

**https://0x48piraj.github.io/pslab.fossasia.org/404.html
https://0x48piraj.github.io/pslab.fossasia.org/500.html**

> Sample PR Accepted : https://github.com/fossasia/2014.fossasia.org/pull/32
Added for easing out our reviewers work.

### CODE REVIEW

**Review by vaibhavsingh97 — APPROVED** [review]
LGTM

**Review by nzec — APPROVED** [review]
LGTM!

**Comment by 0x48piraj** [comment]
Ping @CloudyPadmal :100:

**Review by CloudyPadmal — APPROVED** [review]
Nice work! :D 👍 Thank you!!!!

**Pull request merged**
