### PR TITLE
Menu items bold on scroll over

### PR DESCRIPTION
**Pull request by idealadarsh**
Fixes https://github.com/fossasia/pslab.fossasia.org/issues/46
Preview: https://adarsh-ideal.github.io/pslab.fossasia.org/
screenshot from 2017-01-13 03-50-25

### CODE REVIEW

**Comment by mariobehling** [comment]
Sorry, this is a misunderstanding. The goal is to have that for the top bar only not for the expanded menu. Thank you.

**Comment by idealadarsh** [comment]
@mariobehling Fixed it.

**Comment by mariobehling** [comment]
* Top menu bar not getting bold on scroll-over on top red area. Expected: It should
* Sub-menu items still getting bold on scroll-over when background is white. Expected: It should not

**Comment by mariobehling** [comment]
@adarsh-ideal As this issue has not be solved entirely and there has been many months of inactivity, I guess this will not finished by you. I am closing this PR therefore.

**Pull request closed without merging**
