### PR TITLE
issue #39 have fixed

### PR DESCRIPTION
**Pull request by AKostiv8**
fixed the issue #39 added missed photo of mentor, fixed links and made
text readable in the mentor/developer section and made footer section
more user-friendly

### CODE REVIEW

**Comment by AKostiv8** [comment]
Live link https://akostiv8.github.io/pslab.fossasia.org/

**Review by hemantjadon — CHANGES_REQUESTED** [review]
Icons still not correct according to the design.

Use svgs take hints from `font-awsome`

**Comment by AKostiv8** [comment]
@hemantjadon  can you give an example, I can't read your minds?

**Comment by AKostiv8** [comment]
@hemantjadon  I have done your request

**Comment by hemantjadon** [comment]
Looks better now, Please decrease the size of both logos a bit, and squash your commits so that we can merge.

**Pull request closed without merging**
